### PR TITLE
Make get_placeholders interceptable

### PR DESCRIPTION
**Pull request by SegiNyn**
Hello, can we make the `get_placeholders` function interceptable so that we can change the value of the `context`

### CODE REVIEW

**Comment by ThiefMaster** [comment]
What's the need for it? Do you want to fully replace the placeholders? Otherwise just register a signal handler to return your own placeholders.

TBH I'm slightly against making this one interceptable since it feels very hacky to intercept this...

**Comment by SegiNyn** [comment]
We have an object type that uses a different set of placeholders and we want to be able to call a different signal that is not 'designer-fields' to get the correct placeholders when printing badges for that type.  So we use the type of the registration to know which signal to call. This is how I was using it: 

```
registration = args.arguments['kwargs']['registration']
if isinstance(registration, Accreditation):
    args.arguments['context'] = 'accreditation-designer-fields'
```

**Comment by ThiefMaster** [comment]
but `get_placeholders` is usually not called with any kwargs.. so how do you get the `registration` kwarg there to begin with?

**Comment by SegiNyn** [comment]
https://github.com/indico/indico/blob/e0ae8f6be08ec14076f3f4969809bd0f6e719e35/indico/modules/events/registration/badges.py#L84

**Comment by ThiefMaster** [comment]
Sorry, but I don't think this is a good idea to add upstream. `get_placeholders('designer-fields')` is called in more places, and in some of them there's no `registration` available at all, so it'd be very inconsistent.

**Comment by SegiNyn** [comment]
Okay, please is there another way you could suggest for us to this?

**Comment by ThiefMaster** [comment]
Unfortunately not... Do you have the link to your custom code using it? Maybe I get an idea by looking at your code..

**Comment by SegiNyn** [comment]
The placeholder is being used like this: 

https://github.com/UNOG-Indico/indico-un/blob/09cb91036239b3dca1f6ac62a7641e4c01af6a10/un/modules/designer/patches.py#L57

https://github.com/UNOG-Indico/indico-un/blob/09cb91036239b3dca1f6ac62a7641e4c01af6a10/un/modules/designer/patches.py#L81

**Comment by SegiNyn** [comment]
And I wanted to change it to this: 

https://github.com/UNOG-Indico/indico-un/blob/a3bdf5055bd642444df9759c1437f6f61aa8a4c1/un/modules/designer/__init__.py#L64

**Comment by ThiefMaster** [comment]
patch `get_placeholders` and if it's called with the normal context, use e.g. `flask.g.rh` to check the RH used (or the list of registrations used) in order to find out if you want to use your custom context instead

**Comment by SegiNyn** [comment]
Okay, I'll try that. Thank you very much.

**Pull request closed without merging**
