### PR TITLE
Get plugin data for SingleDatePicker interval

### PR DESCRIPTION
**Pull request by vtran99**
Request to change component SigngleDatePicker to get interval for years before/after from plugin's object,
as our users would like to have a bigger range when scrolling years of Date fields.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
For which fields do you want to change this? If it's reasonable maybe we can just set a better range in the core...

**Comment by vtran99** [comment]
> For which fields do you want to change this? If it's reasonable maybe we can just set a better range in the core...

Our Business Analysts demand to have a big range, I set this in our plugin:
{ yearsBefore: 50, yearsAfter: 50 }
But maybe it's too broad for you ...
The best would be: those values set from a configuration file for each Indico installation :-)

**Comment by vtran99** [comment]
> > > For which fields do you want to change this? If it's reasonable maybe we can just set a better range in the core...
> > 
> > 
> > Our Business Analysts demand to have a big range, I set this in our plugin: { yearsBefore: 50, yearsAfter: 50 } But maybe it's too broad for you ... The best would be: those values set from a configuration file for each Indico installation :-)
> 
> is there any specific instance of this field for which you need that range? or is it for every single instance?

The demand came mainly when users input their birth date which most of time is 20-50 years before current year, so the scrolling is not obvious for them (they're stuck)... other fields we use are expiration date of ID/passport which will require 10 years range for convenience.

**Comment by vtran99** [comment]
I checked with our Business Analysts and the issue is not only on registration form but for all places where the Date Picker is used, and in particular "My profile" where we also have Birth date field, ID expiration data...

If I'm not mistaken, the Date Picker component will also be reshaped soon for accessibitity purpose (but unfortunately not before we deploy new 3.3 version), so how about accepting that plugin change then rediscuss about a better way to do with the accessibility change ?

**Comment by ThiefMaster** [comment]
IMHO the general problem is that there's simply no context... so the plugin cannot know for which date picker it's changing the defaults.

FWIW, even when making it more accessible in some way, we'd still have the same problem - unless of course the date picker there uses something that's not just a dropdown but rather something similar to what e.g. the Windows calendar does (seeing all years and somewhat quickly scrolling through them).

Anyway, if we go for the plugin hook: What do you think about returning a callable instead of an object, so you can pass the originally-provided yearsBefore + yearsAfter? That way you can at least guess from the original prop values whether it makes sense to override or not... For example when yearsBefore is set to `0`, you probably don't want to override, because it's a field that only accepts a future date.

I would also replace the ternary with more "classic" code to avoid the linter error.

**Comment by vtran99** [comment]
> IMHO the general problem is that there's simply no context... so the plugin cannot know for which date picker it's changing the defaults.
> 
> FWIW, even when making it more accessible in some way, we'd still have the same problem - unless of course the date picker there uses something that's not just a dropdown but rather something similar to what e.g. the Windows calendar does (seeing all years and somewhat quickly scrolling through them).
> 
> Anyway, if we go for the plugin hook: What do you think about returning a callable instead of an object, so you can pass the originally-provided yearsBefore + yearsAfter? That way you can at least guess from the original prop values whether it makes sense to override or not... For example when yearsBefore is set to `0`, you probably don't want to override, because it's a field that only accepts a future date.
> 
> I would also replace the ternary with more "classic" code to avoid the linter error.

In fact, the idea is to change the default range for ALL date pickers independently of context: 
5 (or whatever value) by default, and custom value for whoever wants to use plugin o change it.
I can add a test to check value got > 0 but will use a callable if you insist (just afraid there is issue with delay of results with react..) as the callable will also need to implement the logic value > 0.

**Comment by vtran99** [comment]
Code modified as requested, please review again.

**Review by ThiefMaster — APPROVED** [review]

**Pull request merged**
