### PR TITLE
Add template hook to event management title

### PR DESCRIPTION
**Pull request by meluru**
- Adds `event-management-after-title` template hook
- Fixes `banner` class margins

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Looks fine. What exactly are you fixing in the banner margins? And example how it's broken without the fix? I see a tiny (1px or something in that area) shift between master and your branch, but nothing significant.

**Comment by meluru** [comment]
When we add more content to the banner with the hook, 10% is more than 17px and things overlap.

**Comment by ThiefMaster** [comment]
OK, makes sense. I was afraid the fix would break the alignment fixed in #4389 but that's not the case so everything is ok!

However, I don't think this fix needs a changelog entry since it's not broken in the core, and the hook also did not exist in a previous version.

**Comment by meluru** [comment]
Great! I've removed the changelog entry.

**Pull request merged**
