### PR TITLE
Room booking message: fix typo in French translation (SearchResultCount.jsx:190)

### LINKED ISSUE #4069: Room booking: typo in French translation (SearchResultCount.jsx:190)
The French message in https://github.com/indico/indico/blob/cebcf67dc090379e1bbd665fe2e9e13ff09edcf8/indico/translations/fr_FR/LC_MESSAGES/messages-react.po#L1934 has a spelling error: `cete interval` should be `cet intervalle`.

### PR DESCRIPTION
**Pull request by jouvin**
Fixes #4069

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Thanks, but the translations are managed on Transifex, so this fix would get lost the next time we pull from there. If you sign up on https://www.transifex.com/indico/indico/ you can request access to the project and then contribute fixes there directly.

**Comment by jouvin** [comment]
@ThiefMaster sorry for missing this, I'll sign up on transifex

**Comment by mic4ael** [comment]
Hey @jouvin, as far as I can tell you are already a member of our French translation team. So, you should be able to translate/fix things once you log in ;)

**Comment by jouvin** [comment]
@mic4ael yes, I applied to the project yesterday evening and uploaded the fix. Please confirm that everything is ok in Transifex as it was my first time with it...

**Pull request closed without merging**
