### PR TITLE
Support event roles in ACL field

### LINKED ISSUE #4185: Create a component for event roles assignment
Currently track permissions dialog allows only assigning users and groups. The goal is to implement a react component that will take care of assigning event roles there. This is only front end task, the back end already exists.

### PR DESCRIPTION
**Pull request by ThiefMaster**
closes #4185

### CODE REVIEW

**Comment by meluru** [comment]
The code looks good so far. 

I'd only add a bit more spacing between the role name and permissions, because right now it looks squeezed compared to user.

image

**Comment by ThiefMaster** [comment]
Thought about it, the problem is that it starts looking a bit funny if you don't have any roles

**Comment by meluru** [comment]
> Thought about it, the problem is that it starts looking a bit funny if you don't have any roles

How would it look like if the spacing was only for roles? (so that all entries have the same height)

**Comment by ThiefMaster** [comment]
Oh you mean vertical spacing. I thought you mean horizontal spacing between the icon and the title.

**Comment by ThiefMaster** [comment]
an empty `List.Description` doesn't render at all (or is collapsed). so i'd have to replace that with some custom placeholder in case of roles or local groups (which are shown in the same way). i'd say that's not really in the scope of this PR ;)

**Pull request merged**
