### PR TITLE
Support strike-out text in markdown

### PR DESCRIPTION
**Pull request by ThiefMaster**
I'm surprised we didn't already have this....

### CODE REVIEW

**Comment by paulmenzel** [comment]
What Markdown dialect is that. I can’t find this in the [“original” syntax](https://daringfireball.net/projects/markdown/syntax).

**Comment by ThiefMaster** [comment]
~~test~~ - not sure if it originates from GFM but i've seen it in many places: github, discord. mattermost

**Review by paulmenzel — APPROVED** [review]
> Not sure if it originates from GFM but i've seen it in many places: github, discord. mattermost

I’d mention that in the commit message. Nevertheless sounds good.

**Comment by ThiefMaster** [comment]
Hmm actually I'd have though CommonMark also supports it but apparently it's not in the core spec there. There's some [discussion](https://talk.commonmark.org/t/strikeout-threw-out-strikethrough-strikes-out-throughout/820) about it as an extension but I got tired after reading through some of it...

**Pull request merged**
