### PR TITLE
Add a workaround to fix reportlab bug and generate smaller PDF

### PR DESCRIPTION
**Pull request by tomako**
This PR is about to set a workaround to fix reportlab `ImageReader` bug and generate smaller PDF. 
For further details see comment in code.

The bug is still there even in the latest reportlab version (4.2.2). I sent a bug report but I think it's worth to fix this problem until they manage to fix that on their side. Especially because in some cases the large PDF files cause issues.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Thanks! I changed it a bit to avoid the whole Pillow round-trip. Please give it a try to confirm that it indeed properly compresses the image, but I'd expect it to since it's receiving exactly what you were passing, except without reading+saving the image an extra time.

**Comment by tomako** [comment]
Yes, it works and I see the benefit of that. Beside skipping the conversion here and there this solution is not just a temporary workaround.
On the other hand it breaks things on our side since we have our own placeholders providing images. Surely we can update them, though. So if you think it's safe to rewrite image placeholders it's fine for me.

**Comment by ThiefMaster** [comment]
Yes, it should be very straightforward, similar to what I did for the QR code:

```py
buf = BytesIO()
your_pillow_image.save(buf)
buf.seek(0)
return buf
```

**Comment by tomako** [comment]
Ah, I've done that part already. 
I meant whether it is safe introducing a breaking change because of other Indico users.

**Comment by ThiefMaster** [comment]
Changelog message added: 75945d4d07

**Pull request merged**
