### PR TITLE
Use `www-data` instead of `nginx` group in debian config

### PR DESCRIPTION
**Pull request by ClundXIII**
The wrong group is used in a few places, it should be `www-data`:

```
/etc/uwsgi-indico.ini
/etc/systemd/system/indico-uwsgi.service
/etc/systemd/system/indico-celery.service
```

Additionally if you use debian 11, no external package sources are needed! (postgres is v13 and the python stuff is installed locally for the user anyway).

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I think this depends on the debian version. I'm 100% sure that the guide worked the last time I tested it. So probably this changed only with Debian 11.

Maybe we should just update our docs for Debian 11 (when was it released?) and assume people with an older version have the necessary skills to adapt (w/o step by step guidance for the differences there)...

**Comment by ClundXIII** [comment]
> I think this depends on the debian version. I'm 100% sure that the guide worked the last time I tested it. So probably this changed only with Debian 11.

debian 11 and 10 user `www-data`. And if I remember correctly, debian 9 as well.

**Comment by ClundXIII** [comment]
> Maybe we should just update our docs for Debian 11 (when was it released?) and assume people with an older version have the necessary skills to adapt (w/o step by step guidance for the differences there)...

That sounds reasonable, yes.

**Comment by ThiefMaster** [comment]
I don't remember during which version I wrote the docs, but could it be a difference between the cloud/VM images and docker images? When I tested them I created VMs on OpenStack using the latest debian cloud images

**Comment by ClundXIII** [comment]
Okay, I think this should be okay. I also added the startcluster command which is needed sometimes.

**Comment by axu-trex** [comment]
Wait ... so if all dependencies are already packaged for Debian, then we could just start packaging indico for Debian/sid as well? I had been thinking about this already, but I was daunted by the prospect of wading through all the dependencies and packaging them all...

**Comment by ThiefMaster** [comment]
old PR, will be covered when I update our install docs for the latest OS versions before the v3.3 release

**Comment by ThiefMaster** [comment]
According to my latest tests on the Ubuntu 24.04 prerelease cloud image:

- When using nginx from the nginx repos, it runs as `nginx:nginx`
- When using nginx from the debian/ubuntu repos, it runs as `www-data:www-data`

**Pull request closed without merging**
