### PR TITLE
List of contributions improvements

### PR DESCRIPTION
**Pull request by OmeGak**
Some commits I had unmerged from before Christmas.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Why devel? Sounds like something for `master`

**Comment by ThiefMaster** [comment]
Also, you have unrelated commits the PR

**Comment by OmeGak** [comment]
It's basically everything that I had on my devel branch. I can change the title of the PR if you prefer it to reflect this fact.

**Comment by ThiefMaster** [comment]
I think at least the attachment stuff could go into 1.9.6

**Pull request merged**
