### PR TITLE
Minor layout improvement in category overview

### PR DESCRIPTION
**Pull request by nop33**

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Can we also capitalize the options?

**Comment by nop33** [comment]
YES we can!

**Comment by florv** [comment]
The bold "Period" and "Detail level" look more emphasized to me than "Display options".

**Comment by nop33** [comment]
@florv I think it looks fine, what do the others think?

**Comment by ThiefMaster** [comment]
Looks fine for me.

ss

**Comment by florv** [comment]
Yep, problem with my screen that displayed the gray in "Period" almost as dark black as "Display options"…

**Comment by ThiefMaster** [comment]
Merged 52336cd

**Pull request closed without merging**
