### PR TITLE
Images folder name and nginx group name are modified

### PR DESCRIPTION
**Pull request by Ahmet-Kaplan**
web/static folder name is changed to web/htdocs. So, nginx.conf file should be updated.

Also, nginx web user is named www-data.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Thanks, but your change to the folder name is not correct:

- Version 2.0 (obsolete) and 2.1 (current stable) use htdocs: https://docs.getindico.io/en/stable/installation/production/debian/nginx/#configure-uwsgi-nginx
- Version 2.2 (under development) and newer use static: https://docs.getindico.io/en/latest/installation/production/debian/nginx/#configure-uwsgi-nginx

The regexps for the aliases are also different - you need to use the correct docs for the version you are using..

**Comment by ThiefMaster** [comment]
About the users: Which Debian version are you using?

**Comment by Ahmet-Kaplan** [comment]
I am using Debian 9 bionic.

**Comment by ThiefMaster** [comment]
I'm not sure what "Debian Bionic" is. AFAIK Bionic is an Ubuntu release. Could you post the output of `lsb_release -a`?

**Comment by Ahmet-Kaplan** [comment]
Really sorry about that. It's Ubuntu bionic. 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by ThiefMaster** [comment]
Then they must have changed this between xenial and bionic... I did all testing with 16.04 when writing the docs... great, updating the docs for that won't be fun since debian most likely still has a different username.

**Comment by ThiefMaster** [comment]
I just tested the install guide on the latest Ubuntu 18.04.2 and it works perfectly with with the `nginx` group, so I don't think there is any need to switch to `www-data`.

**Pull request closed without merging**
