### PR TITLE
Option to send copy of an email to sender as well

### LINKED ISSUE #2225: Add "send copy to me" option to standard e-mail dialogs
Unless there is a good reason to hide it, it seems to be useful for most users.
Internal reference: `CHG34180`

### PR DESCRIPTION
**Pull request by DavidAndreev**
Closes #2225

### CODE REVIEW

**Comment by ThiefMaster** [comment]
emailing registrants uses a different RH than emailing event persons / users

**Comment by DavidAndreev** [comment]
So far I added this only to email dialog from Roles page, should this be also available when sending registration emails ? Cause there we already have preview email functionality so maybe its not necessary.  If required I can also put it to email dialogs when sending emails to reviewers after [ #2858](https://github.com/indico/indico/pull/2858) gets merged and when sending emails with survey links [#2869](https://github.com/indico/indico/pull/2869) , but again not sure if its needed.

**Comment by ThiefMaster** [comment]
I think it's not so much about previews but about having a copy in your mailbox

**Comment by DavidAndreev** [comment]
Ok so can I use the first registration from array as an example of an email sent ? Like we do when displaying the preview? Cause I need to pass some registration in order to replace the placeholders.

**Pull request merged**
