### PR TITLE
Use better default log levels

### PR DESCRIPTION
**Pull request by mic4ael**
Changed log levels for standard error and main indico handlers.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Your CERN email address doesn't seem to be linked to your GitHub account yet (the commits aren't shown as done by you)

**Comment by ThiefMaster** [comment]
Instead of "Issue #1829" in the title I'd put `fixes #1829` in the commit message (third line). It should also be rather concise in the first line and not have clutter. e.g. this (feel free to amend and forcepush):

```
Use better default log levels

fixes #1829
```

**Comment by mic4ael** [comment]
Ok, thanks a lot for the advices ;) I will keep those in mind.

**Comment by ThiefMaster** [comment]
I think the stderr logger should use INFO, not ERROR - it's used for the celery logger which has some rather useful output (for development - for production it shouldn't be enabled at all)

**Comment by ThiefMaster** [comment]
Merged 62ccb4526573401daa295949276c8478e2f2d86a

**Pull request closed without merging**
