### PR TITLE
Small corrections to apache.rst and upgrade.rst

### PR DESCRIPTION
**Pull request by shesselbach**
Debian apache.rst: Add two more dependencies: postgresql-contrib-9.6 and virtualenv

upgrade.rst: Changed `--archive-dir /opt/indico/archive` to `--archive-dir /opt/indico-legacy/archive` in Copy & Paste example for "Running indico-migrate"

### CODE REVIEW

**Comment by ThiefMaster** [comment]
On which exact OS version did you need to install these two packages? `python-virtualenv` should be fine to get virtualenv and IIRC the postgres extensions worked fine  when I was testing without having to install the contrib package too

**Comment by ThiefMaster** [comment]
> root@indico-fromscratch:~# apt install postgresql-9.6 libpq-dev python-virtualenv
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libldap-2.4-2 libpq5 libsasl2-2 libsasl2-modules libsasl2-modules-db libsensors4 pgdg-keyring postgresql-client-9.6 postgresql-client-common postgresql-common **postgresql-contrib-9.6** python-chardet-whl python-colorama-whl python-distlib-whl python-html5lib-whl python-pip-whl python-requests-whl
  python-setuptools-whl python-six-whl python-urllib3-whl python3-pkg-resources python3-virtualenv ssl-cert sysstat **virtualenv**


Any chance you have some option enabled to no not install "extra" packages?

**Comment by ThiefMaster** [comment]
OK I see, apparently you somehow have `--no-install-recommends` enabled. I wonder if adding `--install-recommends` is the better choice...

**Comment by ThiefMaster** [comment]
It's only the two packages you added (also in the nginx-based setup), but based on https://unix.stackexchange.com/questions/77053/apt-installing-more-packages-than-specified-as-dependencies/77076#77076 I'd go for `--install-recommends`.

**Comment by shesselbach** [comment]
I installed Indico on a newly setup Debian Jessie VM from our Linux experts. And indeed on these machines recommended packeges never get installed, i.e. `--no-install-recommends` is somehow the default. I agree that `--install-recommends` might be the better solution. I will update the PR.

**Comment by ThiefMaster** [comment]
Thanks! Can you also update nginx.rst since it uses the same packages for postgres/virtualenv?

**Comment by ThiefMaster** [comment]
thanks, merged!

**Pull request merged**
