### PR TITLE
Add registrations number to Event exporter (#5594)

### PR DESCRIPTION
**Pull request by amandahla**
Add a registration field with the number of registrations for a given event to the Event exporter (HTTP-API).

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I'm not completely opposed to adding this, but it'd certainly need to be implemented more thoroughly and take into account things like whether the registration count of a particular registration form is being published (remember: anyone who can see the event can get its data from the API as well), and it should use the same logic as the displayed registration count does. 

The `active_registration_count` and `publish_registration_count` properties of a RegistrationForm might be useful for this.

**Comment by amandahla** [comment]
Thanks for bringing this up, I wasn't aware of the privacy setting. 
I did this change but now the registration number is wrong and I'm not sure why. I'll investigate more.

**Comment by ThiefMaster** [comment]
I don't think this should take the privacy settings into account (nor whether the user exporting the event is registered). They are meant for revealing lists w/ names, but not for the counts.

**Comment by ThiefMaster** [comment]
Closing this one considering that the PR is currently stale and it's not clear which number to expose

**Pull request closed without merging**
