### PR TITLE
Fix JS library import in docs

### PR DESCRIPTION
**Pull request by nop33**

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Why not switch to another CDN that's not broken?
https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/hmac-sha1.js

**Comment by nop33** [comment]
Thanks, I was looking for a link but couldn't find one. Cheers.

**Comment by ThiefMaster** [comment]
Did you test it? The jquery update is from a years-old version and while I don't think we do anything fancy that might have changed giving it a quick try would be great to see if it still works

**Comment by nop33** [comment]
Yes I tested it, I opened the `html` file locally and the URL generation works fine

**Pull request merged**
