### PR TITLE
Add form populate to RegistrationPrivacyForm

### PR DESCRIPTION
**Pull request by vtran99**
Request to add form.populate to RegistrationPrivacyForm for the purpose of updating custom fields.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Originally the idea was to make sure all the form fields can be populated properly...

**Comment by vtran99** [comment]
> Originally the idea was to make sure all the form fields can be populated properly...

Done, but for the change log: I can't find way to not duplicate code.

**Comment by ThiefMaster** [comment]
You could use `self.regform.populate_from_dict(form.data)` and then make sure `form.data` contains all the data in the proper format. That method already returns you a list of changes.

**Comment by vtran99** [comment]
With your suggestion : 
`changes = self.regform.populate_from_dict(form.data, skip={'visibility'})
`
I have issue because our form has some combined fields (like visibility) which are not attributes of regform, so the regform.populate_from_dict => 
ValueError: RegistrationForm has no attribute '...'
And I can't skip them like skip visibility.

**Comment by vtran99** [comment]
Code modified with populate_from_dict, please review again.

**Review by ThiefMaster — APPROVED** [review]

**Pull request merged**
