### PR TITLE
Improve i18n format checks

### LINKED ISSUE #6538: Fix faulty checking for empty string and extend to more formats
**Describe the bug**
The `check-format-strings` function should warn us when we remove `{}` from a translation string. Currently with empty braces this is not the case (see below). We also want to extend the feature so that we support `%(...)` notation.

**To Reproduce**
1. Go to a translation file
2. Change a `msgstr` that contains `{}` to not contain that `{}` anymore.
3. Run `indico i18n check-format-strings`
4. It should show that there were `No issues found!`

**Screenshots**
image

### PR DESCRIPTION
**Pull request by AjobK**
Closes #6538

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Indeed, but I wouldn't worry since I'd pull from transifex first and then remove the commit from this PR after rebasing it (that way we can nicely squash-merge this one).

**Comment by AjobK** [comment]
> Indeed, but I wouldn't worry since I'd pull from transifex first and then remove the commit from this PR after rebasing it (that way we can nicely squash-merge this one).

I can also simply remove that commit from this PR, it's not a problem as I have it separately anyway and it's all in transifex

**Comment by AjobK** [comment]
Removed a ton of the fixed translations, but they are in transifex anyway

**Comment by ThiefMaster** [comment]
FYI I just updated from transifex and committed those to master. So if you rebase any broken strings that have already been fixed should be fine and possibly no longer fail the CI here

**Comment by tomasr8** [comment]
I'd also update the comment here:

https://github.com/indico/indico/blob/4f698a223a528cddb8ffc0ea402b883f1786bba6/indico/cli/i18n.py#L673-L676

**Comment by AjobK** [comment]
> I'd also update the comment here:
> 
> https://github.com/indico/indico/blob/4f698a223a528cddb8ffc0ea402b883f1786bba6/indico/cli/i18n.py#L673-L676

I'll just remove it because it is not relevant anymore and documenting babel behavior here does not seem right

**Comment by ThiefMaster** [comment]
> and documenting babel behavior here does not seem right

If it's no longer relevant fine to remove it, but I disagree with this statement. Usually such comments come from someone who dug into the code of the library to figure out why something was working on a certain (weird) way, and such a comment then saves someone else time doing the same thing later, e.g. when wondering why those other format placeholders are not covered.

**Pull request merged**
