### PR TITLE
Use smaller rb splash image

### LINKED ISSUE #6465: change filetype for globe.png
Could we change the filetype for globe.png (size ~2.9MB) to .webp?
The .webp file has only ~0.213MB

globe.webp was processed with cwebp (default settings)
[globe.zip](https://github.com/user-attachments/files/16493597/globe.zip)

### PR DESCRIPTION
**Pull request by bbb-user-de**
closes #6465

### CODE REVIEW

**Comment by bbb-user-de** [comment]
resolved #6465

**Review by GovernmentPlates — CHANGES_REQUESTED** [review]
Thanks for the PR!

Just one thing: the `globe.png` file should be removed as we are now using the `.webp` file.

**Comment by bbb-user-de** [comment]
you are right 👍😉

**Comment by tomasr8** [comment]
Judging by the CI failure, we probably need to add the `.webp` format to our webpack config as well:
https://github.com/indico/indico/blob/5167d8c065e04ca468764babeffd9f5287a3af60/webpack/base.mjs#L392

**Review by GovernmentPlates — APPROVED** [review]

**Review by ThiefMaster — APPROVED** [review]
Thanks, really useful!

**Pull request merged**
