### PR TITLE
Fix Content-Type param from encoding to charset per S3.1.4 RFC5545

### PR DESCRIPTION
**Pull request by imranyusuff**
Trivial change that addresses issue #5228.

### CODE REVIEW

**Comment by imranyusuff** [comment]
Also I am thinking if the attachment filename can be moved to `Content-Disposition` instead.

**Comment by javfg** [comment]
Thank you for the PR, @imranyusuff!

The change seems to be working properly, and you are right on the parameter being named wrong. Good catch. But I've double checked in Thunderbird and Outlook and it was also working before for me. Out of curiosity, can you tell me which client is failing for you?

> Also I am thinking if the attachment filename can be moved to `Content-Disposition` instead.

Sounds good, you can add go ahead and add that change too.

**Comment by jhyeon** [comment]
> Out of curiosity, can you tell me which client is failing for you?

For me [Gnus](https://www.gnus.org/) failed.

@imranyusuff thank you!

**Comment by imranyusuff** [comment]
> Thank you for the PR, @imranyusuff!
> 
> The change seems to be working properly, and you are right on the parameter being named wrong. Good catch. But I've double checked in Thunderbird and Outlook and it was also working before for me. Out of curiosity, can you tell me which client is failing for you?
> 
> > Also I am thinking if the attachment filename can be moved to `Content-Disposition` instead.
> 
> Sounds good, you can add go ahead and add that change too.

I have read carefully RFC 2183 which describe the `Content-Disposition` field. The intent is to tell the browser (or relevant client) whether to display the part as either inline or as an attachment. So need to be clear here what indico intend to present this attached vCalendar file.

Also, I also trying to find out if `filename` is actually supposed to be inside `Content-Type` field in the first place?

**Comment by ThiefMaster** [comment]
Please keep merge commits out of your PR, and make sure to keep it based on 3.1.x, and not master.

**Comment by imranyusuff** [comment]
Oh no. Something wrong here. I think I messed up my branch.

**Comment by ThiefMaster** [comment]
`git reset --hard 3.1.x` and then `git cherry-pick ...` your actual commits.

And in case you are using some weird IDE feature to manage Git, it's best to not do that but use the normal `git` command line tool.

**Comment by imranyusuff** [comment]
Created new PR #5258 and closing this one.

**Pull request closed without merging**
