### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by erempel**
Added instructions for precompiling all of the python modules

### CODE REVIEW

**Comment by ThiefMaster** [comment]
We do not encourage installing Indico without using a virtualenv anymore (and I believe with 2.0 we won't even officially support installing it outside a virtualenv anymore).  So I guess the chance that the installation path is not writable is extremely low.

**Comment by pferreir** [comment]
@ThiefMaster we "don't encourage" it but don't discourage it either. IIRC we don't include virtualenv in the docs. I suggest we open a ticket for 2.0 in which we will properly explain how to set up Indico with virtualenv.

**Comment by ThiefMaster** [comment]
#1737

**Comment by pferreir** [comment]
Ah, had forgotten about that. Then, I guess that's the best thing to do. It's already set as a "blocker" in 2.0.

@erempel, sorry, I think we would rather wait for 2.0 and properly explain things than encourage a behaviour that we don't think is the best and we are not following either. Thanks for the contribution anyway!

**Pull request closed without merging**
