### PR TITLE
Fix alignment on management pages

### LINKED ISSUE #4299: Fix alignment on management pages
This is especially bad and noticeable in category management with the actions next to the title:

image

...but also less strongly in event management:

image

---

This is how it looked like in 2.2:

image

image

---

The tricky part is to make sure it doesn't start pushing down the menu in event management, otherwise adding a `margin-top` would be enough...

### PR DESCRIPTION
**Pull request by ParthS007**
closes #4299 
Screenshot from 2020-04-06 14-18-57

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Unfortunately the change results in the menu being pushed further down in case of a subtitle (like the event creator information in case of event management) - ie exactly what is mentioned in the original issue:

> The tricky part is to make sure it doesn't start pushing down the menu in event management, otherwise adding a margin-top would be enough...

**Comment by mic4ael** [comment]
Hey, I don't know what you had done before but what about just removing the `margin` on the `.group` element?
```diff
diff --git i/indico/web/client/styles/base/_layout.scss w/indico/web/client/styles/base/_layout.scss
index 2db273434f..ee2f817f30 100644
--- i/indico/web/client/styles/base/_layout.scss
+++ w/indico/web/client/styles/base/_layout.scss
@@ -107,7 +107,6 @@ body > * {
         margin-right: 30px;

         .group:first-child {
-            margin-top: 5px;
             margin-bottom: 23px;

             a {
```

**Comment by ParthS007** [comment]
Removing the `margin-top` from here will move the menu column more upwards, in this issue, I am trying to keep `switch display button` and title on the same baseline.

**Comment by mic4ael** [comment]
> Removing the `margin-top` from here will move the menu column more upwards, in this issue, I am trying to keep `switch display button` and title on the same baseline.

Yeah, ofc. But is that really a problem? They will still be on the same baseline.

**Comment by ThiefMaster** [comment]
IMHO it looks bad if there are different spacings above the menu in event/category management

**Comment by mic4ael** [comment]
Ahh.. my bad.. I see now what you mean. I will have a quick look into that

**Comment by mic4ael** [comment]
So, the misalignment is mainly caused by SemanticUI and their CSS rules changing `line-height`. Removing it from the affected nodes fixes the misalignment. But yeah, that will not fix the issue with the menus

**Comment by ThiefMaster** [comment]
Layout-wise it looks fine now. Unless there's a much better solution or any problems caused by this one (I didn't find any) I'm inclined to merge it the way it is now...

**Comment by mic4ael** [comment]
> Layout-wise it looks fine now. Unless there's a much better solution or any problems caused by this one (I didn't find any) I'm inclined to merge it the way it is now...

Looks fine to me as well. I just wanted to mention what actually caused the issue.

**Pull request merged**
