### PR TITLE
Small improvements for the maintenance scripts

### PR DESCRIPTION
**Pull request by andriish**
The update is related only to the build scripts.
 - use explicit name of python executable x 2
 - assure the current directory is in sys.path
 
Best regards,

Andrii

### CODE REVIEW

**Comment by ThiefMaster** [comment]
The changes look fine, just wondering why you needed them. With a proper virtualenv setup, the correct `python` should already be in the $PATH...

**Comment by andriish** [comment]
Hi @ThiefMaster ,

I think we spoke about that once. But at some point, I had an idea to package indico in RPMs to make the installation of the whole ecosystem just with `dnf install python-indico` and configure everything with  `dnf install myconfig-indico` or so.
So I did that. But found some really minor issues in indico.

Best regards,

Andrii

**Comment by andriish** [comment]
The name of python interpreter in my case is `python3` as I do not use the virtual environment

**Comment by andriish** [comment]
Hi @ThiefMaster ,

would you merge this one?

Best regards,

Andrii

**Comment by ThiefMaster** [comment]
The interpreter change looks fine. What's the reason for the sys.path change?

**Comment by andriish** [comment]
Hi @ThiefMaster ,

Could you, please, have a look?
so far I've reverted the changes to with sys.path.
It makes sense to create a separate MR if I remember why that was needed.


Andrii

**Pull request merged**
