### PR TITLE
Js updates 1

### PR DESCRIPTION
**Pull request by bpedersen2**
Regenerate package-lock.json to get the latest update core-js to latest supported version.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
and everything works fine? the last time i tried to touch core-js (years ago) there was a huge load of errors...

**Comment by bpedersen2** [comment]
Yes, with older versions I also  encountered some problems, but the latest tests are actually working (one sympton was, that  the user search dialogs were in-operable). This  did not occur in my test now.

**Comment by bpedersen2** [comment]
Seems the test suite uses a much older nodejs ( 14.x ) while I did it with node 18.x LTS.

**Comment by ThiefMaster** [comment]
let's bump that to node 18 (current LTS)

**Pull request closed without merging**
