### PR TITLE
Fix not passing date format to DatePicker

### PR DESCRIPTION
**Pull request by foxbunny**
This fixes a regression after an earlier refactor where I changed the format-passing to a proper attribute.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
How can I trigger the bug this PR fixes? So far I can't notice any behavioral difference in the registration form between master and your branch...

I first thought maybe it's the incorrect first-day-of-week and not using the translated initial of the weekday (I even changed the locale to de_DE have one where I know for sure that the first day of a week is monday), but this in broken both in master and with your PR (if you could fix that in here as well it'd be great though!)

image

**Comment by ThiefMaster** [comment]
It looks like the `format` attribute is not used anywhere since it's currently taken from the `[data-format]` element?

```
      const dateFormat = formatDescription.textContent
        .split(':')[1]
        .trim()
        .toLowerCase();
```

**Comment by foxbunny** [comment]
> It looks like the format attribute is not used anywhere since it's currently taken from the [data-format] element?

Sent another PR this morning regarding this.

**Comment by foxbunny** [comment]
> I first thought maybe it's the incorrect first-day-of-week and not using the translated initial of the weekday (I even changed the locale to de_DE have one where I know for sure that the first day of a week is monday), but this in broken both in master and with your PR (if you could fix that in here as well it'd be great though!)

Ok, I'll look into this.

**Comment by ThiefMaster** [comment]
A fix for the bug in the screenshot would be nice to have nonetheless :p

**Comment by ThiefMaster** [comment]
Thanks!

**Pull request closed without merging**
