### PR TITLE
Trying to update also the overwritten patch

### PR DESCRIPTION
**Pull request by DirkHoffmann**

### CODE REVIEW

**Comment by DirkHoffmann** [comment]
Sorry, this was nonsense!!! (Wrong direction.)
Where is the undo button?

**Comment by ThiefMaster** [comment]
Trying out GitHub features? ;)

Anyway, some (somewhat rather general) suggestions:

- If there are conflict markers after finishing a merge/rebase, something went wrong.
- You usually do not want merge commits in a pull request
- Any custom patches should be from a separate branch against master
- Usually no development should be done at all in master
- When updating your local master, it's useful to use `git pull --ff-only` - that avoids performing a merge (so it simply fails if it cannot "fast-forward" to the newest commit from the remote repo).

**Comment by DirkHoffmann** [comment]
Yes, not so obvious. In principle I followed instructions from github. There were too many changes since my last update from the indico/indico repository that nothing was automatic.
However, I was amazed that the so much praised git merging failed to recognise that the only change I had in my local directory had been pulled a couple of years ago already and tried to apply it again. Now I am left with a repository that tries to go back in history, the typical pitfall for beginners in CVS or SVN. But I though that could not happen any more with … git! :-)

**Comment by ThiefMaster** [comment]
If you don't have any local changes you care about, the easiest solution (besides `rm -rf` and cloning again) is to `git reset --hard upstream/master` (assuming `upstream` is the remote pointing to our main repo). Afterwards you'd simply `git push --force origin master` to bring your *master* branch on GitHub up-to-date.

**Comment by DirkHoffmann** [comment]
```shell
$ git reset --hard upstream/master
fatal: ambiguous argument 'upstream/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
```

**Comment by ThiefMaster** [comment]
What does `git remote -v` say?

In my case the output is this (origin is my fork, upstream the main repo, both accessed via SSH):

```
[adrian@pcitcis001:~/dev/indico/src:payment]> git remote -v
origin  git@github.com:ThiefMaster/indico.git (fetch)
origin  git@github.com:ThiefMaster/indico.git (push)
upstream        git@github.com:indico/indico.git (fetch)
upstream        git@github.com:indico/indico.git (push)
```

**Comment by DirkHoffmann** [comment]
Should be equivalent:
```shell
$ git remote -v
origin  git@github.com:DirkHoffmann/indico.git (fetch)
origin  git@github.com:DirkHoffmann/indico.git (push)
upstream    https://github.com/indico/indico.git (fetch)
upstream    https://github.com/indico/indico.git (push)
```
(Just tried with ` git@github.com:indico/indico.git`, and the result is the same.)

**Comment by ThiefMaster** [comment]
Ok, how about `git branch -a`? Maybe you ended up creating a *local* branch called `upstream/master`? Actually, you can simply try deleting such a branch using `git branch -D upstream/master`

**Comment by DirkHoffmann** [comment]
```shell
$ git branch -a
  indico-master
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/burotel
  remotes/origin/exp-instant-messaging
  remotes/origin/fix-more-exceptions
  remotes/origin/master
  remotes/origin/new-improved-taskdaemon
  remotes/origin/new-webex
  remotes/origin/prov-dual-interface
  remotes/origin/v0.97-series
  remotes/origin/v0.98-series
  remotes/origin/v0.98.2
  remotes/origin/v0.98b1
  remotes/origin/v0.98b2
$ git branch -D upstream/master
error: branch 'upstream/master' not found.
```

**Comment by ThiefMaster** [comment]
Oh, you probably never fetched upstream! `git fetch upstream`

**Comment by ThiefMaster** [comment]
Oh, you probably never fetched upstream!

    git fetch upstream

**Comment by DirkHoffmann** [comment]
Yes, that makes do. Thank you!
I was just wondering how I had made the merge, if I never git-fetched before. But I git-pulled the indico/indico repo. I admit this is still a bit a mystery to me, and `man git-pull` states pull=fetch+merge, so I am still confused. But time will tell, if I am able to adopt git …

**Comment by ThiefMaster** [comment]
You probably used a url in the git pull call. That way you fetch from a remote repo without actually adding it as a remote. 

Anyway, signing off for the night. There's this weird thing called work tomorrow :p

**Comment by DirkHoffmann** [comment]
:+1:

**Pull request closed without merging**
