### PR TITLE
Hide late warning in rb for events

### LINKED ISSUE #1630: "It's late" warning shows up even when date/time is forced (book within events)
Steps to reproduce:
 1. Event management area
 2. Click "Room Booking"
 3. Book room for meeting
 4. If current time fits requirements, warning will show up even though the date and time are being overridden

"It's late" bug

### PR DESCRIPTION
**Pull request by jacquesd**
- Hide the late warning message when booking a room in an event with fixed
   date and time
 - fix #1630

### CODE REVIEW

**Comment by jacquesd** [comment]
Changes submitted

**Comment by pferreir** [comment]
Waiting for Adrian's suggestions to be checked...

**Comment by ThiefMaster** [comment]
I'm fine with the latest state of the code. It's not 100% perfect but when we looked at it we both agreed that "cleaning" it up further would make it both less readable and more complex.

**Comment by pferreir** [comment]
OK, then.

**Comment by pferreir** [comment]
Merged in 58ebe5c.

**Pull request closed without merging**
